font: JetBrainsMono Nerd Font 16
background: "#1e1e2e"
color: "#cdd6f4"
border: "#f5c2e7"
separator: ":"
border_width: 2
corner_r: 0
padding: 3
rows_per_column: 12
column_padding: 25
anchor: center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0
inhibit_compositor_keyboard_shortcuts: true
auto_kbd_layout: true
menu:
  - key: "d"
    desc: Open Fuzzel
    cmd: fuzzel
  - key: "a"
    desc: Open Alacritty
    cmd: alacritty
  - key: "f"
    desc: Open Freetube
    cmd: /opt/FreeTube/freetube
  - key: "s"
    desc: Open Steam
    cmd: steam
  - key: "m"
    desc: Minecraft
    submenu:
      - key: "p"
        desc: Open Pandora 
        cmd: pandora-launcher
      - key: "l"
        desc: Open Prism Launcher 
        cmd: prismlauncher
  - key: "e"
    desc: Open Bemoji
    cmd: bemoji
  - key: "b"
    desc: Open Browser
    cmd: "xdg-open http:"
  - key: q
    desc: Open Qalculate
    cmd: qalculate-gtk
  - key: "u"
    desc: Power
    submenu:
      - key: "s"
        desc: Shutdown
        cmd: systemctl poweroff
      - key: "r"
        desc: Reboot
        cmd: systemctl reboot
      - key: "e"
        desc: Soft-reboot
        cmd: systemctl soft-reboot
      - key: "f"
        desc: Firmware-setup
        cmd: systemctl reboot --firmware-setup
      - key: "l"
        desc: Lock
        cmd: loginctl lock-session
