border_color=0x313244ff
border_px=2
focus_color=0xf5c2e7ff
gap_inner_horizontal=0
gap_inner_vertical=0
gap_outer_horizontal=0
gap_outer_vertical=0
global_color=0xcba6f7ff
maximized_screen_color=0xa6e3a1ff
overlay_color=0x94e2d5ff
root_color=0x313244ff
scratchpad_height_ratio=0.9
scratchpad_width_ratio=0.8
scratchpad_color=0x89b4faff
urgent_color=0xf38ba8ff
