bordercolor=0x313244ff
borderpx=2
focuscolor=0xf5c2e7ff
gappih=0
gappiv=0
gappoh=0
gappov=0
globalcolor=0xcba6f7ff
maximizescreencolor=0xa6e3a1ff
overlaycolor=0x94e2d5ff
rootcolor=0x313244ff
scratchpad_height_ratio=0.9
scratchpad_width_ratio=0.8
scratchpadcolor=0x89b4faff
urgentcolor=0xf38ba8ff
