bind=SUPER,r,reload_config
bind=SUPER,d,spawn,wlr-which-key
bind=SUPER,Return,spawn,alacritty
bind=SUPER,a,spawn,alacritty
bind=SUPER,f,spawn,xdg-open http:
bind=SUPER,b,spawn,xdg-open http:
bind=SUPER,m,quit
bind=SUPER+SHIFT,s,spawn_shell,noctalia msg screenshot-region
bind=SUPER,q,killclient,
bind=SUPER,Tab,focusstack,next
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right
bind=SUPER+SHIFT,w,spawn_shell,~/.config/mango/redstart-noctalia
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=ALT,space,togglefloating,
bind=ALT,a,togglemaximizescreen,
bind=ALT,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,
bind=SUPER,i,minimized,
bind=SUPER,o,toggleoverlay,
bind=SUPER+SHIFT,i,restore_minimized
bind=ALT,z,toggle_scratchpad
bind=SUPER,x,switch_proportion_preset,
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0
bind=Alt,1,tag,1,0
bind=Alt,2,tag,2,0
bind=Alt,3,tag,3,0
bind=Alt,4,tag,4,0
bind=Alt,5,tag,5,0
bind=Alt,6,tag,6,0
bind=Alt,7,tag,7,0
bind=Alt,8,tag,8,0
bind=Alt,9,tag,9,0
bind=alt+shift,Left,focusmon,left
bind=alt+shift,Right,focusmon,right
bind=SUPER+Alt,Left,tagmon,left
bind=SUPER+Alt,Right,tagmon,right
bind=ALT+SHIFT,X,incgaps,1
bind=ALT+SHIFT,Z,incgaps,-1
bind=ALT+SHIFT,R,togglegaps
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
bind=NONE,XF86AudioMute,spawn_shell,noctalia msg volume-mute
bind=NONE,XF86AudioRaiseVolume,spawn_shell,noctalia msg volume-up 5
bind=NONE,XF86AudioLowerVolume,spawn_shell,noctalia msg volume-down 5
bind=NONE,XF86MonBrightnessUp,spawn_shell,noctalia msg brightness-up 5
bind=NONE,XF86MonBrightnessDown,spawn_shell,noctalia msg brightness-down 5
