exec_once=~/.config/mango/autostart.sh
source=./animations.conf
source=./appearance.conf
source=./binds.conf
source=./effects.conf
source=./env.conf
source=./input.conf
source=./layout.conf
source=./misc.conf
source=./monitors.conf
source=./overview.conf
source=./tagrule.conf
