disable_trackpad=0
drag_lock=1
mouse_middle_button_emulation=0
mouse_natural_scrolling=0
numlockon=0
repeat_delay=600
repeat_rate=25
swipe_min_threshold=1
tap_and_drag=1
tap_to_click=1
trackpad_disable_while_typing=1
trackpad_left_handed=0
trackpad_natural_scrolling=0
xkb_rules_layout=de
