axis_bind_apply_timeout=100
cursor_size=24
cursor_theme=Bibata-Original-Classic
drag_tile_to_tile=1
enable_floating_snap=0
focus_cross_monitor=0
focus_cross_tag=0
focus_on_activate=1
idleinhibit_ignore_visible=0
no_border_when_single=0
sloppyfocus=1
snap_distance=30
warpcursor=1
